protocols:
  - id: "opcuaProtocol"
    type: "opcua"
    config:
      server_url: "opc.tcp://0.0.0.0:4840/freeopcua/server/"
      server_name: "MockPhysicalTwin"
      namespace: "http://examples.mockphysicaltwin.com"
      security_mode: "None"
      security_policy: "None"
      username: null
      password: null
  - id: "mqttProtocol"
    type: "mqtt"
    config:
      broker_ip: "192.168.0.115"
      broker_port: 1883
      username: null
      password: null

devices:
  - id: "OPCUA_Device"
    protocol_id: "opcuaProtocol"
    sensors:
      - id: "numericSensor"
        type: "numeric"
        update_time_ms: 200
        min_val: 0
        max_val: 100
        initial_value: 0
        node_id: "ns=2;s=Device1.numericSensor"
      - id: "booleanSensor"
        type: "boolean"
        update_time_ms: 100
        initial_value: false
        node_id: "ns=2;s=Device1.booleanSensor"
      - id: "randomStringSensor"
        type: "random_string"
        value_len: 10
        update_time_ms: 300
        node_id: "ns=2;s=Device1.randomStringSensor"
      - id: "fixedStringSensor"
        type: "fixed_string"
        value: "test-fixed-string"
        update_time_ms: 500
        node_id: "ns=2;s=Device1.fixedStringSensor"
      - id: "sensor_accel"
        type: "numeric"
        update_time_ms: 100
        csv_file: "/app/data/accelerometer_data_seconds.csv"
        value_columns: ["accel_x", "accel_y", "accel_z"]
        node_id: "ns=2;s=Device1.sensor_accel"
    actuators:
      - id: "demoActuator"
        type: "string"
        initial_value: "ON"
  - id: "MQTT_Device"
    protocol_id: "mqttProtocol"
    sensors:
      - id: "numericSensor"
        type: "numeric"
        update_time_ms: 200
        min_val: 0
        max_val: 100
        initial_value: 0
      - id: "booleanSensor"
        type: "boolean"
        update_time_ms: 100
        initial_value: false
      - id: "randomStringSensor"
        type: "random_string"
        value_len: 10
        update_time_ms: 300
      - id: "fixedStringSensor"
        type: "fixed_string"
        value: "test-fixed-string"
        update_time_ms: 500
      - id: "sensor_accel"
        type: "numeric"
        update_time_ms: 100  # 1 second in milliseconds
        csv_file: "/app/data/accelerometer_data_seconds.csv"
        value_columns: [ "accel_x", "accel_y", "accel_z" ]
    actuators:
      - id: "demoActuator"
        type: "string"
        initial_value: "ON"

independent_communication: False
device_update_delay_ms: 100  # Update every 10 seconds if independent_communication is False