destinations:
  d1:
    type: local
    directory: ./output
    
sources:
  s1:
    type: random
    rv: uniform
    interval: 1

devices:
  device:
    vars:
      room1: living_room
      room2: bedroom
    sensors:
      sensor1:
        source: s1
        destinations:
          d1:
            endpoint: "{device}/{sensor}/{var:room1}/{source}"
            