destinations:
  foo:
    type: local
    directory: ./output
    processor_path: /home/nricciardi/Repositories/python-mock-physical-twin/processor.py
    processor_function: p

  foo2:
    type: local
    directory: ./output
    
sources:
  foo:
    type: csv
    file: ./data/humidity.csv
    rotate: false
    interval: 0.5

  foo2:
    type: random
    rv: uniform
    interval: 1

  foo3:
    type: random
    rv: uniform
    interval: 1

devices:
  foo:
    vars:
      room1: living_room
      room2: bedroom
    sensors:
      foo:
        source: foo
        # ^^^ buffering, mantiene l'ultimo valore e lo invia ogni 2 secondi
        destinations:
          foo:
            endpoint: "{device}/{sensor}/{var:room1}/{source}"
            