protocols:
  - id: "simulationBridge"
    type: "simulation_bridge_amqp"
    config:
      client_config:
        rabbitmq:
          host: "localhost"
          port: 5672
          vhost: "/"
          username: "guest"
          password: "guest"
          tls: false
        exchanges:
          input_bridge:
            name: "ex.input.bridge"
            type: "topic"
            durable: true
          bridge_result:
            name: "ex.bridge.result"
            type: "topic"
            durable: true
        queue:
          result_queue_prefix: "Q"
          durable: true
          routing_key: "*.result"
        digital_twin:
          dt_id: "dt"
          routing_key_send: "dt"
      simulation_api: "simulation.yaml"
      aggregate:
        device_id: "device1"
        sensor_id: "bridgeAggregate"
        sensor_config:
          type: "string"
          update_time_ms: 1000
      routes:
        - when:
            type: "all"
          publish:
            exchange: "ex.bridge.result"
            routing_key: "sim.data"
            payload: "{raw}"
        - when:
            type: "json_path"
            path: "agents"
            foreach: true
          publish:
            exchange: "ex.bridge.result"
            routing_key: "sim.agent.{index}"
            payload:
              x: "{0}"
              y: "{1}"
        - when:
            type: "json_path"
            path: "distance"
          publish:
            exchange: "ex.bridge.result"
            routing_key: "sim.distance"
            payload: "{value}"
        - when:
            type: "json_path"
            path: "step"
          publish:
            exchange: "ex.bridge.result"
            routing_key: "sim.step"
            payload: "{value}"
devices:
  - id: "device1"
    protocol_id: "simulationBridge"
    sensors:
      - id: "bridgeAggregate"
        type: "string"
        update_time_ms: 60000
        initial_value: {}
    actuators: []
independent_communication: False
device_update_delay_ms: 1000
